name: Feature Request
about: Suggest an improvement or new feature for LaravelFS.
title: "[FEATURE] "
labels: enhancement
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please provide as much detail as possible.
  - type: input
    id: feature
    attributes:
      label: Feature Description
      description: A concise description of the feature.
      placeholder: "Describe the feature you would like to see..."
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain why this feature is needed or how it would benefit LaravelFS.
      placeholder: "Explain the benefits of the feature..."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Provide any additional context or screenshots.
      placeholder: "Add any other context here..."
